<a href="https://colab.research.google.com/github/HarshiniArulmani2006/Harshini-codeboosters-2026/blob/main/Day_3/Day_3_data_engineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install requests --quiet
import pandas as pd
import numpy as np
import requests
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
print('All libraries imported successfully!!')
print(f'pandas:{pd.__version__}')
print(f'requests:{requests.__version__}')

All libraries imported successfully!!
pandas:2.2.2
requests:2.32.4

In [ ]:
raw_df=pd.read_csv('/content/messy_sales_data.csv')
print(f'Raw data loaded: {raw_df.shape[0]} rows,{raw_df.shape[1]} columns')
print(f'Columns:{raw_df.columns.tolist()}')
print('\nFirst 5 rows:')
raw_df.head()

Raw data loaded: 30 rows,9 columns
Columns:['order_id', 'customer_name', 'product', 'category', 'quantity', 'unit_price', 'order_date', 'city', 'sales_rep']

First 5 rows:

,order_id,customer_name,product,category,quantity,unit_price,order_date,city,sales_rep
0,1001,Ramesh Kumar,Laptop,Electronics,2.0,45000,2024-01-05,Mumbai,Anil Sharma
1,1002,Priya Nair,NaN,Electronics,1.0,15000,2024-01-07,Delhi,Sunita Rao
2,1003,AMIT VERMA,Keyboard,Accessories,3.0,1200,2024-01-08,Bangalore,Anil Sharma
3,1004,Sunita Patel,Monitor,Electronics,NaN,22000,2024-01-10,Chennai,Ravi Kumar
4,1005,Ramesh Kumar,Laptop,Electronics,2.0,45000,2024-01-05,Mumbai,Anil Sharma

In [ ]:
#diagonosis all data quality problems before fixing
print(' DATA QUALITY DIAGONOSIS REPORT')
#missing values
print('\n 1.Missing values per column:')
print(raw_df.isnull().sum())
#duplicates
print('\n 2.Duplicates rows: {raw_df.duplicated().sum()}')
#datatypes
print('\n 3.Data types:')
print(raw_df.dtypes)
#unique value in text columns(spot inconsistences)
print('\n 4.UNIQUE CATEGORIES:',raw_df['category'].unique)
print('4 Sample customer names:',raw_df['customer_name'].dropna().unique()[:8])
print('4 Sample order_date values:',raw_df['order_date'].unique()[:6])

 DATA QUALITY DIAGONOSIS REPORT

 1.Missing values per column:
order_id         0
customer_name    2
product          1
category         1
quantity         3
unit_price       0
order_date       0
city             0
sales_rep        0
dtype: int64

 2.Duplicates rows: {raw_df.duplicated().sum()}

 3.Data types:
order_id           int64
customer_name     object
product           object
category          object
quantity         float64
unit_price         int64
order_date        object
city              object
sales_rep         object
dtype: object

 4.UNIQUE CATEGORIES: <bound method Series.unique of 0     Electronics
1     Electronics
2     Accessories
3     Electronics
4     Electronics
5     Accessories
6     Electronics
7     Accessories
8     Electronics
9     Accessories
10    Electronics
11    Accessories
12    Electronics
13    Electronics
14    Accessories
15    Accessories
16    Accessories
17    Electronics
18    Electronics
19    Accessories
20    Electronics
21    Accessories
22    Electronics
23    Electronics
24    Accessories
25    Electronics
26            NaN
27    Electronics
28    Accessories
29    Accessories
Name: category, dtype: object>
4 Sample customer names: ['Ramesh Kumar' 'Priya Nair' 'AMIT VERMA' 'Sunita Patel' 'kiran mehta'
 'Deepak Singh' 'Ananya Das' 'Vikram Iyer']
4 Sample order_date values: ['2024-01-05' '2024-01-07' '2024-01-08' '2024-01-10' '07-01-2024'
 '2024-01-12']

In [ ]:
df=raw_df.copy()
print(f'Working copy created: {df.shape}')
print('raw_df is untouched - we can always reset by runnning df=raw_df.copy()')

Working copy created: (30, 9)
raw_df is untouched - we can always reset by runnning df=raw_df.copy()

In [ ]:
df.head(10)

,order_id,customer_name,product,category,quantity,unit_price,order_date,city,sales_rep
0,1001,Ramesh Kumar,Laptop,Electronics,2.0,45000,2024-01-05,Mumbai,Anil Sharma
1,1002,Priya Nair,NaN,Electronics,1.0,15000,2024-01-07,Delhi,Sunita Rao
2,1003,AMIT VERMA,Keyboard,Accessories,3.0,1200,2024-01-08,Bangalore,Anil Sharma
3,1004,Sunita Patel,Monitor,Electronics,NaN,22000,2024-01-10,Chennai,Ravi Kumar
4,1005,Ramesh Kumar,Laptop,Electronics,2.0,45000,2024-01-05,Mumbai,Anil Sharma
5,1006,kiran mehta,Mouse,Accessories,10.0,800,07-01-2024,Pune,Sunita Rao
6,1007,Deepak Singh,Headphones,Electronics,2.0,3500,2024-01-12,Hyderabad,Ravi Kumar
7,1008,NaN,Webcam,Accessories,1.0,2500,2024-01-13,Mumbai,Anil Sharma
8,1009,Ananya Das,Laptop,Electronics,1.0,45000,2024-01-15,Kolkata,Sunita Rao
9,1010,Vikram Iyer,Keyboard,Accessories,5.0,1200,2024-01-15,Chennai,Ravi Kumar

In [ ]:
#handle missing values
#why two times sum means total sum of missing values of total dataset simply all columns missing values,
# if we want to just know the just one column missing values have to use single value
df = raw_df.copy() # Reset df to ensure 'quantity' column is clean
print('Before fixing nulls:',df.isnull().sum().sum(),'total missing values')
df['customer_name'].fillna('Unknown Customer',inplace=True)
median_qty=df['quantity'].median()
df['quantity'].fillna(median_qty,inplace=True)
print(f'Filled missing quantity with median: {median_qty}')
df['category'].fillna('Uncategorized',inplace=True)
print('After fixing nulls:',df.isnull().sum().sum(),'total missing values')

Before fixing nulls: 7 total missing values
Filled missing quantity with median: 2.0
After fixing nulls: 1 total missing values

In [ ]:
print("Missing Values in Product Column")
print(f'The missing values in product column count is:{df['product'].isnull().sum()}')
df['product'].fillna('Unknown Product',inplace=True)
print(f'After missing values handling:{df['product'].isnull().sum()}')

Missing Values in Product Column
The missing values in product column count is:1
After missing values handling:0

In [ ]:
#remove duplicates
print(f'Before deduplication:{len(df)} rows')
print(f'Duplicate rows:{df.duplicated().sum()}')
print("\nDuplicate rows:")
print(df[df.duplicated(keep=False)][['order_id','customer_name','product','order_date']])
df.drop_duplicates(inplace=True)
print(f'\nAfter deduplication:{len(df)} rows')
print(f'Rows removed: {len(raw_df)-len(df)}')

Before deduplication:30 rows
Duplicate rows:0

Duplicate rows:
Empty DataFrame
Columns: [order_id, customer_name, product, order_date]
Index: []

After deduplication:30 rows
Rows removed: 0

In [ ]:
print('Sample dates before parsing:')
print(df['order_date'].head(8).tolist())
df['order_date']=pd.to_datetime(
    df['order_date'],
    dayfirst=False,
    errors='coerce'
)
nat_count=df['order_date'].isnull().sum()
print(f'\nUnparsable dates(NaT):{nat_count}')
df['year']=df['order_date'].dt.year
df['month']=df['order_date'].dt.month
df['month_name']=df['order_date'].dt.strftime('%B')
#df['day']=df['order_date'].dt.day
print('\nSample dates after parsing:')
print(df[['order_date','year','month','month_name']].head(5))

Sample dates before parsing:
['2024-01-05', '2024-01-07', '2024-01-08', '2024-01-10', '2024-01-05', '07-01-2024', '2024-01-12', '2024-01-13']

Unparsable dates(NaT):2

Sample dates after parsing:
  order_date    year  month month_name
0 2024-01-05  2024.0    1.0    January
1 2024-01-07  2024.0    1.0    January
2 2024-01-08  2024.0    1.0    January
3 2024-01-10  2024.0    1.0    January
4 2024-01-05  2024.0    1.0    January

In [ ]:
print('Sample dates before parsing:')
print(df['order_date'].head(8).tolist())
df['order_date']=pd.to_datetime(
    df['order_date'],
    dayfirst=True,
    errors='coerce'
)
nat_count=df['order_date'].isnull().sum()
print(f'\nUnparsable dates(NaT):{nat_count}')
df['year']=df['order_date'].dt.year
df['month']=df['order_date'].dt.month
df['month_name']=df['order_date'].dt.strftime('%B')
df['order_date'] = df['order_date'].dt.strftime('%d-%m-%Y')
print('\nSample dates after parsing:')
print(df[['order_date','year','month','month_name']].head(5))

Sample dates before parsing:
[Timestamp('2024-01-05 00:00:00'), Timestamp('2024-01-07 00:00:00'), Timestamp('2024-01-08 00:00:00'), Timestamp('2024-01-10 00:00:00'), Timestamp('2024-01-05 00:00:00'), NaT, Timestamp('2024-01-12 00:00:00'), Timestamp('2024-01-13 00:00:00')]

Unparsable dates(NaT):2

Sample dates after parsing:
   order_date    year  month month_name
0  05-01-2024  2024.0    1.0    January
1  07-01-2024  2024.0    1.0    January
2  08-01-2024  2024.0    1.0    January
3  10-01-2024  2024.0    1.0    January
4  05-01-2024  2024.0    1.0    January

In [ ]:
print('Sample dates before parsing:')
print(df['order_date'].head(8).tolist())
df['order_date']=pd.to_datetime(
    df['order_date'],
    dayfirst=True,
    errors='coerce'
)
nat_count=df['order_date'].isnull().sum()
print(f'\nUnparsable dates(NaT):{nat_count}')
df['year']=df['order_date'].dt.year
df['month']=df['order_date'].dt.month
df['month_name']=df['order_date'].dt.strftime('%B')
df['day_name']=df['order_date'].dt.day_name()
df['order_date'] = df['order_date'].dt.strftime('%d-%m-%Y')
print('\nSample dates after parsing:')
print(df[['order_date','year','month','month_name','day_name']].head(5))

Sample dates before parsing:
['05-01-2024', '07-01-2024', '08-01-2024', '10-01-2024', '05-01-2024', nan, '12-01-2024', '13-01-2024']

Unparsable dates(NaT):2

Sample dates after parsing:
   order_date    year  month month_name   day_name
0  05-01-2024  2024.0    1.0    January     Friday
1  07-01-2024  2024.0    1.0    January     Sunday
2  08-01-2024  2024.0    1.0    January     Monday
3  10-01-2024  2024.0    1.0    January  Wednesday
4  05-01-2024  2024.0    1.0    January     Friday

In [ ]:
print('Before Standarization:',df['customer_name'].unique()[:6])
df['customer_name']=(
    df['customer_name']
    .str.strip()
    .str.title()
)
print('After Standarization:',df['customer_name'].unique()[:6])
mask=(df['product']=='Keyboard') & (df['category']=='Electronics')
df.loc[mask,'category']='special one'
print(df[['product', 'category']])

Before Standarization: ['Ramesh Kumar' 'Priya Nair' 'AMIT VERMA' 'Sunita Patel' 'kiran mehta'
 'Deepak Singh']
After Standarization: ['Ramesh Kumar' 'Priya Nair' 'Amit Verma' 'Sunita Patel' 'Kiran Mehta'
 'Deepak Singh']
            product       category
0            Laptop    Electronics
1   Unknown Product    Electronics
2          Keyboard    Accessories
3           Monitor    Electronics
4            Laptop    Electronics
5             Mouse    Accessories
6        Headphones    Electronics
7            Webcam    Accessories
8            Laptop    Electronics
9          Keyboard    Accessories
10          Monitor    Electronics
11          USB Hub    Accessories
12           Laptop    Electronics
13       Headphones    Electronics
14           Webcam    Accessories
15            Mouse    Accessories
16         Keyboard    Accessories
17          Monitor    Electronics
18           Laptop    Electronics
19          USB Hub    Accessories
20       Headphones    Electronics
21           Webcam    Accessories
22           Laptop    Electronics
23         Keyboard    special one
24            Mouse    Accessories
25       Headphones    Electronics
26          Monitor  Uncategorized
27           Laptop    Electronics
28          USB Hub    Accessories
29           Webcam    Accessories

In [ ]:
df['quantity']=pd.to_numeric(df['quantity'],errors='coerce').astype(int)
df['unit_price']=pd.to_numeric(df['unit_price'],errors='coerce')
df['revenue']=df['quantity']*df['unit_price']
print('Revenue Column created:')
print(df[['customer_name','quantity','unit_price','revenue']].head(10))
mask=(df['product']=='Keyboard') & (df['category']=='Electronics')
df.loc[mask,'category']='special one'
print(df[['product', 'category']])

Revenue Column created:
      customer_name  quantity  unit_price  revenue
0      Ramesh Kumar         2       45000    90000
1        Priya Nair         1       15000    15000
2        Amit Verma         3        1200     3600
3      Sunita Patel         2       22000    44000
4      Ramesh Kumar         2       45000    90000
5       Kiran Mehta        10         800     8000
6      Deepak Singh         2        3500     7000
7  Unknown Customer         1        2500     2500
8        Ananya Das         1       45000    45000
9       Vikram Iyer         5        1200     6000
            product       category
0            Laptop    Electronics
1   Unknown Product    Electronics
2          Keyboard    Accessories
3           Monitor    Electronics
4            Laptop    Electronics
5             Mouse    Accessories
6        Headphones    Electronics
7            Webcam    Accessories
8            Laptop    Electronics
9          Keyboard    Accessories
10          Monitor    Electronics
11          USB Hub    Accessories
12           Laptop    Electronics
13       Headphones    Electronics
14           Webcam    Accessories
15            Mouse    Accessories
16         Keyboard    Accessories
17          Monitor    Electronics
18           Laptop    Electronics
19          USB Hub    Accessories
20       Headphones    Electronics
21           Webcam    Accessories
22           Laptop    Electronics
23         Keyboard    special one
24            Mouse    Accessories
25       Headphones    Electronics
26          Monitor  Uncategorized
27           Laptop    Electronics
28          USB Hub    Accessories
29           Webcam    Accessories

In [ ]:
df.dropna(inplace=True)

In [ ]:
print('Post Cleaning Report')
print(f'Original rows:{len(raw_df)}')
print(f'Cleaned rows:{len(df)}')
print(f'Rows removed:{len(raw_df)-len(df)}(duplicates)')
print(f'Missing Values:{df.isnull().sum().sum()}(should be 0)')
print(f'Duplicates:{df.duplicated().sum()}(should be 0)')
print(f'Data nulls:{df['order_date'].isnull().sum()}')
print(f'Revenue NaN:{df['revenue'].isnull().sum()}')
print(f'Categories:{sorted(df['category'].unique())}')
#all check should show clean results
all_clean=(
    df.isnull().sum().sum()==0 and
    df.duplicated().sum()==0
)
print(f'Data Clean Status true means cleaned false means not clened completely:{all_clean}')

Post Cleaning Report
Original rows:30
Cleaned rows:28
Rows removed:2(duplicates)
Missing Values:0(should be 0)
Duplicates:0(should be 0)
Data nulls:0
Revenue NaN:0
Categories:['Accessories', 'Electronics', 'Uncategorized', 'special one']
Data Clean Status true means cleaned false means not clened completely:True